### ISSUE TITLE
SPEACH_AF on new version of AF2

### ISSUE THREAD

**Issue by jdernic** [RSvan/SPEACH_AF#1]
Dear Dr. Stein,

Thank you for developing this very interesting method! I am trying to test it on some fusion proteins, however I have run into a problem when trying to use the modified batch.py file on the newest version of ColabFold (v1.5.2). I understand that the batch file modification was based on the one belonging to the v1.3.0 version. Thus, I wanted to ask if its possible to make it work with the new version or if its a modification that could be easily implemented?

I look forward to your response.

Kind Regards,

Jan

**Comment by RSvan** [comment]
Hi Jan,

The modification in batch.py was to allow for each run to have a different random seed so the same MSA could yield different results. This can be achieved in ColabFold v1.5 with their new command line parameters: random-seed and num-seeds. They are as named, to change the random seed number and to do multiple runs modifying the random seed for each run.

Good luck,
Richard
