### ISSUE TITLE
Initial Alphafold2 structures are relaxed for in silico mutagenesis?

### ISSUE THREAD

**Issue by eunos-1128** [RSvan/SPEACH_AF#2]
Thank you for your work.

I am trying to use SPEACH_AF for my conformer sampling but found that the paper did not say whether there is relaxation of predicted models using colabfold(alphafold2) prior to in silico mutagenesis operation or not.

Is a PDB data of the top model used for in silico mutagenesis of its MSA sequences is relaxed or not?

I'm sorry that this issue is not related to repo's code itself.

Regards,

**Comment by RSvan** [comment]
There is no requirement for using a relaxed structure. The choice of pdb to use is left to the user. The only requirement is that the sequence in the pdb match exactly to the sequence in the MSA that is to be modified.

**Comment by eunos-1128** [comment]
I'll use both of relaxed and unrelaxed structures to learn the difference by in-silico mutagenesis.

Thank you for your answer.
